### ISSUE TITLE
Not working in Mac OSX 10.11.5 

### ISSUE THREAD

**Issue by MagePsycho** [yvoronoy/magento2-bash-completion#2] opened 2016-06-16 21:38 UTC
I simply copied the `magento2-bash-completion` file to `/usr/local/etc/bash_completion.d/` and reload it.
And if you tried to press tab after incomplete command nothing happens.

**Comment by yvoronoy** [comment] 2016-06-17 16:17
Thank you for reporting.
I have tested on Mac OSX 10.11.4 and bash --help
GNU bash, version 3.2.57(1)-release-(x86_64-apple-darwin15)

I will try to check it, and update you soon

**Comment by yvoronoy** [comment] 2016-06-18 21:51
I have checked on MacOSX and it works as expected.
Please check these:
- Ensure you have installed bash-completion. See http://superuser.com/questions/288438/bash-completion-for-commands-in-mac-os-x
- Ensure that you are using /bin/bash (not /bin/sh) http://osxdaily.com/2012/03/21/change-shell-mac-os-x/  
- Try to load it directly by command: `source /usr/local/etc/bash_completion.d/magento2-bash-completion`
- type bin/magento [TAB][TAB]. Don't run it as `php bin/magento` in this case it won't work.

Let me know if it helps you to resolve the issue.

**Comment by MagePsycho** [comment] 2016-06-19 19:13
Works perfectly by following those steps.
Going to write a blog post on this.
Thanks for the useful plugin.

**Comment by MagePsycho** [comment] 2016-06-19 19:20
There is one issue that I noticed.
`bin/magento module:en[TAB]`-> `bin/magento enable` which should be
`bin/magento module:enable`

**Comment by yvoronoy** [comment] 2016-06-19 19:27
Great, share link with me when blog post will be ready 👍 
Unfortunately, I can't reproduce your second issue, it works as expected.
Your can see all commands on line https://github.com/yvoronoy/magento2-bash-completion/blob/master/magento2-bash-completion#L12 there is module:enable command.

**Comment by yvoronoy** [comment] 2016-06-19 19:31
Yesterday I have resolved other issue https://github.com/yvoronoy/magento2-bash-completion/issues/3
So ensure you are using the last version of completion file.

**Comment by yvoronoy** [comment] 2016-06-20 18:45
I'm closing this issue.
Feel free to reopen it, or create a new one if you will have any issues.

Thank you

**Closed as completed by yvoronoy** 2016-06-20 18:45 UTC
